name: 'dbt_apex'
version: '1.0.0'
config-version: 2

profile: 'dbt_apex'

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  dbt_apex:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts